// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzStMLjjF5MVTNrMrlnbRgoFKi_ijEcfY',
    appId: '1:519090387073:web:6c2eb6ab713b5651b4f580',
    messagingSenderId: '519090387073',
    projectId: 'formmhsbaru',
    authDomain: 'formmhsbaru.firebaseapp.com',
    storageBucket: 'formmhsbaru.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbD2sblhu49ugo_jTolWJES9KugRGSvac',
    appId: '1:519090387073:android:eb37b7d294a5d03bb4f580',
    messagingSenderId: '519090387073',
    projectId: 'formmhsbaru',
    storageBucket: 'formmhsbaru.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcl_7YSFBU2RrC_4DQzBufG2hK4VyLxT8',
    appId: '1:519090387073:ios:9a402eac92e7a7f0b4f580',
    messagingSenderId: '519090387073',
    projectId: 'formmhsbaru',
    storageBucket: 'formmhsbaru.appspot.com',
    iosBundleId: 'com.example.formPendaftaran2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzStMLjjF5MVTNrMrlnbRgoFKi_ijEcfY',
    appId: '1:519090387073:web:7591986105f4b611b4f580',
    messagingSenderId: '519090387073',
    projectId: 'formmhsbaru',
    authDomain: 'formmhsbaru.firebaseapp.com',
    storageBucket: 'formmhsbaru.appspot.com',
  );

}